# Introduction to NumPy

Welcome to your NumPy tutorial! **NumPy** (Numerical Python) is the fundamental package for scientific computing in Python. It's essential for data science, machine learning, and numerical analysis.

## What is NumPy?

NumPy provides:
- **Fast, efficient arrays** for storing and manipulating numerical data
- **Mathematical functions** for array operations
- **Tools for linear algebra, statistics, and random number generation**

NumPy arrays are much faster and more memory-efficient than Python lists for numerical operations!

## What You'll Learn

In this notebook, you'll learn:
1. **Creating NumPy arrays** - Different ways to create and initialize arrays
2. **Array properties** - Shape, size, dimensions, and data types
3. **Indexing and slicing** - Accessing and modifying array elements
4. **Array operations** - Element-wise operations and broadcasting
5. **Matrix operations** - Matrix multiplication vs element-wise multiplication
6. **Creating sequences** - Using linspace and arange
7. **Random numbers** - Sampling from uniform and Gaussian distributions

Let's get started!

## Setup - Importing NumPy

First, we need to import NumPy. The standard convention is to import it as `np`:

In [1]:
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.2


## 1. Creating NumPy Arrays

### What is a NumPy Array?

A **NumPy array** (also called an `ndarray`) is a grid of values, all of the same type. Unlike Python lists:
- Arrays are **faster** for numerical operations
- Arrays use **less memory**
- Arrays support **vectorized operations** (operations on entire arrays at once)

### Creating Arrays from Lists

The most common way to create an array is from a Python list:

In [2]:
# ===== 1D ARRAY (VECTOR) =====
# Create array from a list
arr1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1d)
print("Type:", type(arr1d))

# ===== 2D ARRAY (MATRIX) =====
# Create array from a list of lists
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("\n2D array:")
print(arr2d)

# ===== 3D ARRAY =====
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print("\n3D array:")
print(arr3d)

1D array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

2D array:
[[1 2 3]
 [4 5 6]]

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

NumPy arrays have several important properties:

In [3]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Array:")
print(arr)
print("\n--- Properties ---")
print("Shape (dimensions):", arr.shape)      # (3, 4) = 3 rows, 4 columns
print("Number of dimensions:", arr.ndim)     # 2 (2D array)
print("Total elements:", arr.size)           # 12 elements
print("Data type:", arr.dtype)               # int64 (or int32 on some systems)
print("Item size (bytes):", arr.itemsize)    # 8 bytes per element
print("Total size (bytes):", arr.nbytes)     # 96 bytes total

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

--- Properties ---
Shape (dimensions): (3, 4)
Number of dimensions: 2
Total elements: 12
Data type: int64
Item size (bytes): 8
Total size (bytes): 96


### Special Array Creation Functions

NumPy provides many functions to create arrays quickly:

In [4]:
# ===== ZEROS =====
zeros = np.zeros((3, 4))  # 3x4 array of zeros
print("Zeros array:")
print(zeros)

# ===== ONES =====
ones = np.ones((2, 3))  # 2x3 array of ones
print("\nOnes array:")
print(ones)

# ===== FULL (filled with a specific value) =====
sevens = np.full((2, 2), 7)  # 2x2 array filled with 7
print("\nArray of 7s:")
print(sevens)

# ===== IDENTITY MATRIX =====
identity = np.eye(3)  # 3x3 identity matrix
print("\nIdentity matrix:")
print(identity)

# ===== RANGE OF VALUES =====
range_arr = np.arange(0, 10, 2)  # Start, stop, step (like Python's range)
print("\nRange array (0 to 10, step 2):")
print(range_arr)

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]

Array of 7s:
[[7 7]
 [7 7]]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Range array (0 to 10, step 2):
[0 2 4 6 8]


### Data Types

You can specify the data type when creating arrays:

In [5]:
# Integer array
int_arr = np.array([1, 2, 3], dtype=np.int32)
print("Integer array:", int_arr, "dtype:", int_arr.dtype)

# Float array
float_arr = np.array([1, 2, 3], dtype=np.float64)
print("Float array:", float_arr, "dtype:", float_arr.dtype)

# Convert data type
converted = int_arr.astype(np.float32)
print("Converted to float:", converted, "dtype:", converted.dtype)

# Boolean array
bool_arr = np.array([True, False, True])
print("Boolean array:", bool_arr, "dtype:", bool_arr.dtype)

Integer array: [1 2 3] dtype: int32
Float array: [1. 2. 3.] dtype: float64
Converted to float: [1. 2. 3.] dtype: float32
Boolean array: [ True False  True] dtype: bool


### 🎯 Practice Exercise: Creating Arrays

Try these exercises:

1. Create a 1D array with values from 1 to 10
2. Create a 5x5 array filled with zeros
3. Create a 3x3 array filled with the value 42
4. Create a 4x4 identity matrix
5. Create an array with values from 0 to 20 with step 3 (use `arange`)

In [35]:
# Your code here:
np.arange(1,11)
np.full((5,5), 0)
np.full((3,3), 42)
np.eye(4)
np.arange(0,20, 3)


array([ 0,  3,  6,  9, 12, 15, 18])

## 2. Indexing and Slicing

### Indexing 1D Arrays

Indexing works similar to Python lists, but NumPy provides much more powerful indexing capabilities:

In [7]:
# ===== BASIC INDEXING =====
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("First element (index 0):", arr[0])    # 10
print("Last element (index -1):", arr[-1])   # 50

# ===== SLICING =====
print("\n--- Slicing ---")
print("First 3 elements [0:3]:", arr[0:3])   # [10, 20, 30]
print("From index 2 onwards [2:]:", arr[2:]) # [30, 40, 50]
print("Last 2 elements [-2:]:", arr[-2:])    # [40, 50]
print("Every other element [::2]:", arr[::2])# [10, 30, 50]
print("Reversed [::-1]:", arr[::-1])         # [50, 40, 30, 20, 10]

# ===== MODIFYING VALUES =====
arr[0] = 100
print("\nAfter modifying index 0:", arr)

arr[1:4] = [200, 300, 400]
print("After modifying slice [1:4]:", arr)

Array: [10 20 30 40 50]
First element (index 0): 10
Last element (index -1): 50

--- Slicing ---
First 3 elements [0:3]: [10 20 30]
From index 2 onwards [2:]: [30 40 50]
Last 2 elements [-2:]: [40 50]
Every other element [::2]: [10 30 50]
Reversed [::-1]: [50 40 30 20 10]

After modifying index 0: [100  20  30  40  50]
After modifying slice [1:4]: [100 200 300 400  50]


### Indexing 2D Arrays

For 2D arrays (matrices), you can index using `[row, column]`:

In [8]:
# ===== 2D ARRAY INDEXING =====
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("2D Array:")
print(arr2d)

# Access single element
print("\nElement at row 0, column 2:", arr2d[0, 2])  # 3
print("Element at row 1, column 3:", arr2d[1, 3])    # 8

# Access entire row
print("\nFirst row:", arr2d[0])      # [1, 2, 3, 4]
print("Second row:", arr2d[1])       # [5, 6, 7, 8]

# Access entire column
print("\nFirst column:", arr2d[:, 0])    # [1, 5, 9]
print("Third column:", arr2d[:, 2])      # [3, 7, 11]

# ===== SLICING 2D ARRAYS =====
print("\n--- Slicing 2D Arrays ---")
print("First 2 rows, first 3 columns:")
print(arr2d[0:2, 0:3])

print("\nAll rows, columns 1-3:")
print(arr2d[:, 1:4])

print("\nRows 1-2, all columns:")
print(arr2d[1:3, :])

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at row 0, column 2: 3
Element at row 1, column 3: 8

First row: [1 2 3 4]
Second row: [5 6 7 8]

First column: [1 5 9]
Third column: [ 3  7 11]

--- Slicing 2D Arrays ---
First 2 rows, first 3 columns:
[[1 2 3]
 [5 6 7]]

All rows, columns 1-3:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

Rows 1-2, all columns:
[[ 5  6  7  8]
 [ 9 10 11 12]]


### Boolean Indexing

You can use boolean conditions to select elements:

In [9]:
# ===== BOOLEAN INDEXING =====
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Create boolean mask
mask = arr > 5
print("\nMask (arr > 5):", mask)
print("Elements > 5:", arr[mask])

# More concise
print("\nElements > 5 (concise):", arr[arr > 5])
print("Even numbers:", arr[arr % 2 == 0])
print("Numbers between 3 and 7:", arr[(arr >= 3) & (arr <= 7)])

# ===== MODIFYING WITH BOOLEAN INDEXING =====
arr[arr > 7] = 0  # Set all values > 7 to 0
print("\nAfter setting values > 7 to 0:", arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]

Mask (arr > 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]

Elements > 5 (concise): [ 6  7  8  9 10]
Even numbers: [ 2  4  6  8 10]
Numbers between 3 and 7: [3 4 5 6 7]

After setting values > 7 to 0: [1 2 3 4 5 6 7 0 0 0]


### Fancy Indexing

You can use arrays of indices to select specific elements:

In [10]:
# ===== FANCY INDEXING =====
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("Original array:", arr)

# Select elements at indices 1, 3, 5
indices = [1, 3, 5]
print("\nElements at indices [1, 3, 5]:", arr[indices])

# Works with 2D arrays too
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("\n2D array:")
print(arr2d)

# Select rows 0 and 2
print("\nRows 0 and 2:")
print(arr2d[[0, 2]])

Original array: [10 20 30 40 50 60 70 80 90]

Elements at indices [1, 3, 5]: [20 40 60]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rows 0 and 2:
[[1 2 3]
 [7 8 9]]


### 🎯 Practice Exercise: Indexing and Slicing

Given the array below, complete these tasks:

```python
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
```

1. Extract the element at row 1, column 2 (should be 70)
2. Extract the entire third row
3. Extract the second column
4. Extract a 2x2 subarray from the top-left corner
5. Find all elements greater than 60

In [47]:
# Your code here:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print(arr[1, 2])
print(arr[2, :])
print(arr[:, 1])
print(arr[:2, :2])
print(arr[arr>60])


70
[ 90 100 110 120]
[ 20  60 100]
[[10 20]
 [50 60]]
[ 70  80  90 100 110 120]


## 3. Array Operations

### Element-wise Operations

One of NumPy's greatest strengths is **vectorization** - performing operations on entire arrays without explicit loops:

In [12]:
# ===== ARITHMETIC OPERATIONS =====
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a =", a)
print("b =", b)

print("\n--- Element-wise Operations ---")
print("a + b =", a + b)      # [11, 22, 33, 44]
print("a - b =", a - b)      # [-9, -18, -27, -36]
print("a * b =", a * b)      # [10, 40, 90, 160] (element-wise!)
print("a / b =", a / b)      # [0.1, 0.1, 0.1, 0.1]
print("a ** 2 =", a ** 2)    # [1, 4, 9, 16]
print("b // 3 =", b // 3)    # [3, 6, 10, 13]

# ===== OPERATIONS WITH SCALARS =====
print("\n--- Operations with Scalars ---")
print("a * 10 =", a * 10)    # [10, 20, 30, 40]
print("a + 5 =", a + 5)      # [6, 7, 8, 9]
print("a ** 3 =", a ** 3)    # [1, 8, 27, 64]

a = [1 2 3 4]
b = [10 20 30 40]

--- Element-wise Operations ---
a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
a / b = [0.1 0.1 0.1 0.1]
a ** 2 = [ 1  4  9 16]
b // 3 = [ 3  6 10 13]

--- Operations with Scalars ---
a * 10 = [10 20 30 40]
a + 5 = [6 7 8 9]
a ** 3 = [ 1  8 27 64]


### Universal Functions (ufuncs)

NumPy provides many mathematical functions that operate element-wise:

In [13]:
# ===== MATHEMATICAL FUNCTIONS =====
arr = np.array([1, 4, 9, 16, 25])
print("Array:", arr)

print("\n--- Math Functions ---")
print("Square root:", np.sqrt(arr))       # [1, 2, 3, 4, 5]
print("Exponential:", np.exp([1, 2, 3]))  # [e^1, e^2, e^3]
print("Natural log:", np.log(arr))        # ln(x)
print("Log base 10:", np.log10(arr))      # log10(x)

# ===== TRIGONOMETRIC FUNCTIONS =====
angles = np.array([0, np.pi/2, np.pi])
print("\n--- Trigonometric Functions ---")
print("Angles (radians):", angles)
print("sin:", np.sin(angles))
print("cos:", np.cos(angles))
print("tan:", np.tan(angles))

# ===== ROUNDING =====
decimals = np.array([1.234, 2.567, 3.891])
print("\n--- Rounding ---")
print("Original:", decimals)
print("Round:", np.round(decimals, 2))     # Round to 2 decimals
print("Floor:", np.floor(decimals))        # Round down
print("Ceil:", np.ceil(decimals))          # Round up

Array: [ 1  4  9 16 25]

--- Math Functions ---
Square root: [1. 2. 3. 4. 5.]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Log base 10: [0.         0.60205999 0.95424251 1.20411998 1.39794001]

--- Trigonometric Functions ---
Angles (radians): [0.         1.57079633 3.14159265]
sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

--- Rounding ---
Original: [1.234 2.567 3.891]
Round: [1.23 2.57 3.89]
Floor: [1. 2. 3.]
Ceil: [2. 3. 4.]


### Aggregation Functions

Compute statistics across arrays:

In [14]:
# ===== AGGREGATION =====
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array:", arr)

print("\n--- Aggregation Functions ---")
print("Sum:", np.sum(arr))           # 55
print("Mean:", np.mean(arr))         # 5.5
print("Median:", np.median(arr))     # 5.5
print("Std deviation:", np.std(arr)) # Standard deviation
print("Variance:", np.var(arr))      # Variance
print("Min:", np.min(arr))           # 1
print("Max:", np.max(arr))           # 10
print("Argmin (index of min):", np.argmin(arr))  # 0
print("Argmax (index of max):", np.argmax(arr))  # 9

# ===== AGGREGATION ON 2D ARRAYS =====
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("\n2D Array:")
print(arr2d)

print("\nSum of all elements:", np.sum(arr2d))        # 45
print("Sum of each column (axis=0):", np.sum(arr2d, axis=0))  # [12, 15, 18]
print("Sum of each row (axis=1):", np.sum(arr2d, axis=1))     # [6, 15, 24]
print("Mean of each column:", np.mean(arr2d, axis=0))         # [4, 5, 6]

Array: [ 1  2  3  4  5  6  7  8  9 10]

--- Aggregation Functions ---
Sum: 55
Mean: 5.5
Median: 5.5
Std deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Argmin (index of min): 0
Argmax (index of max): 9

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements: 45
Sum of each column (axis=0): [12 15 18]
Sum of each row (axis=1): [ 6 15 24]
Mean of each column: [4. 5. 6.]


### Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes:

In [15]:
# ===== BROADCASTING =====
# Add a scalar to an array
arr = np.array([1, 2, 3])
print("Array:", arr)
print("Array + 10:", arr + 10)  # [11, 12, 13]

# Add a 1D array to each row of a 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
row = np.array([10, 20, 30])

print("\n2D Array:")
print(arr2d)
print("\nRow:", row)
print("\n2D Array + Row:")
print(arr2d + row)  # Adds [10, 20, 30] to each row

# Add a column
col = np.array([[100], [200], [300]])
print("\nColumn:")
print(col)
print("\n2D Array + Column:")
print(arr2d + col)  # Adds column to each column of arr2d

Array: [1 2 3]
Array + 10: [11 12 13]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row: [10 20 30]

2D Array + Row:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Column:
[[100]
 [200]
 [300]]

2D Array + Column:
[[101 102 103]
 [204 205 206]
 [307 308 309]]


### Caution with Broadcasting
Be careful when using broadcasting, as it can lead to unexpected results if the shapes of the arrays are not compatible. Always check the shapes of your arrays before performing operations to ensure they align as intended.
Notice how depending on the shapes of the arrays, the result can vary significantly. First we added a row vector to a matrix, then a column vector to the same matrix.
For a detailed explanation, refer to the [NumPy broadcasting documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules).

## 4. Matrix Multiplication vs Element-wise Multiplication

This is a crucial distinction in NumPy!

### Element-wise Multiplication

The `*` operator performs **element-wise multiplication** (Hadamard product):

In [16]:
# ===== ELEMENT-WISE MULTIPLICATION =====
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Element-wise multiplication using *
element_wise = A * B
print("\nElement-wise multiplication (A * B):")
print(element_wise)
print("\nExplanation: [1*5, 2*6]")
print("             [3*7, 4*8]")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise multiplication (A * B):
[[ 5 12]
 [21 32]]

Explanation: [1*5, 2*6]
             [3*7, 4*8]


### Matrix Multiplication

For **matrix multiplication** (dot product), use `@` operator or `np.dot()`:

In [17]:
# ===== MATRIX MULTIPLICATION =====
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A (2x2):")
print(A)
print("\nMatrix B (2x2):")
print(B)

# Matrix multiplication using @
matrix_mult1 = A @ B
print("\nMatrix multiplication (A @ B):")
print(matrix_mult1)

# Alternative: using np.dot()
matrix_mult2 = np.dot(A, B)
print("\nMatrix multiplication (np.dot(A, B)):")
print(matrix_mult2)

# Alternative: using matmul
matrix_mult3 = np.matmul(A, B)
print("\nMatrix multiplication (np.matmul(A, B)):")
print(matrix_mult3)

print("\nExplanation of A @ B:")
print("Result[0,0] = 1*5 + 2*7 = 5 + 14 = 19")
print("Result[0,1] = 1*6 + 2*8 = 6 + 16 = 22")
print("Result[1,0] = 3*5 + 4*7 = 15 + 28 = 43")
print("Result[1,1] = 3*6 + 4*8 = 18 + 32 = 50")

Matrix A (2x2):
[[1 2]
 [3 4]]

Matrix B (2x2):
[[5 6]
 [7 8]]

Matrix multiplication (A @ B):
[[19 22]
 [43 50]]

Matrix multiplication (np.dot(A, B)):
[[19 22]
 [43 50]]

Matrix multiplication (np.matmul(A, B)):
[[19 22]
 [43 50]]

Explanation of A @ B:
Result[0,0] = 1*5 + 2*7 = 5 + 14 = 19
Result[0,1] = 1*6 + 2*8 = 6 + 16 = 22
Result[1,0] = 3*5 + 4*7 = 15 + 28 = 43
Result[1,1] = 3*6 + 4*8 = 18 + 32 = 50


### Matrix Multiplication with Different Shapes

In [18]:
# ===== MATRIX MULTIPLICATION WITH DIFFERENT SHAPES =====
# For matrix multiplication: (m x n) @ (n x p) = (m x p)

# Example: (2x3) @ (3x2) = (2x2)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("Matrix A (2x3):")
print(A)
print("\nMatrix B (3x2):")
print(B)

result = A @ B
print("\nResult (2x2):")
print(result)

# ===== VECTOR-MATRIX MULTIPLICATION =====
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print("\n--- Vector-Matrix Multiplication ---")
print("Vector (3,):", vector)
print("\nMatrix (3x2):")
print(matrix)

result = vector @ matrix
print("\nResult (2,):", result)
print("Calculation: [1*1+2*3+3*5, 1*2+2*4+3*6] = [22, 28]")

Matrix A (2x3):
[[1 2 3]
 [4 5 6]]

Matrix B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]

Result (2x2):
[[ 58  64]
 [139 154]]

--- Vector-Matrix Multiplication ---
Vector (3,): [1 2 3]

Matrix (3x2):
[[1 2]
 [3 4]
 [5 6]]

Result (2,): [22 28]
Calculation: [1*1+2*3+3*5, 1*2+2*4+3*6] = [22, 28]


### 🎯 Practice Exercise: Matrix Operations

1. Create two 3x3 matrices A and B with values of your choice
2. Compute the element-wise product of A and B
3. Compute the matrix product of A and B
4. Create a 2x3 matrix C and a 3x4 matrix D, then compute C @ D (should give 2x4 matrix)
5. Verify that A @ B is not equal to B @ A (matrix multiplication is not commutative!)

In [55]:
# Your code here:

mat1 = np.full((3,3), 2)
mat2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("element-wise product of A and B: ", mat1*mat2)
print("matrix product of A and B: ", mat1@mat2)

mat3 = np.array([[1,2,3], [3,4,5]])
mat4 = np.array([[1,2,3,4], [5,6,7,8], [9,0,1,2]])

print("compute C @ D: ", mat3@mat4)

mat1@mat2 == mat2@mat1


element-wise product of A and B:  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
matrix product of A and B:  [[24 30 36]
 [24 30 36]
 [24 30 36]]
compute C @ D:  [[38 14 20 26]
 [68 30 42 54]]


array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

## 5. Creating Sequences with linspace and arange

### np.arange - Range of Values

`np.arange(start, stop, step)` creates an array of evenly spaced values (similar to Python's `range`):

In [20]:
# ===== ARANGE =====
# arange(stop) - from 0 to stop-1
arr1 = np.arange(10)
print("arange(10):", arr1)

# arange(start, stop) - from start to stop-1
arr2 = np.arange(5, 15)
print("\narange(5, 15):", arr2)

# arange(start, stop, step)
arr3 = np.arange(0, 20, 3)
print("\narange(0, 20, 3):", arr3)

# Works with floats
arr4 = np.arange(0, 1, 0.1)
print("\narange(0, 1, 0.1):", arr4)

# Negative step (counting down)
arr5 = np.arange(10, 0, -1)
print("\narange(10, 0, -1):", arr5)

arange(10): [0 1 2 3 4 5 6 7 8 9]

arange(5, 15): [ 5  6  7  8  9 10 11 12 13 14]

arange(0, 20, 3): [ 0  3  6  9 12 15 18]

arange(0, 1, 0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

arange(10, 0, -1): [10  9  8  7  6  5  4  3  2  1]


### np.linspace - Linearly Spaced Values

`np.linspace(start, stop, num)` creates an array of `num` evenly spaced values between `start` and `stop` (inclusive):

In [21]:
# ===== LINSPACE =====
# linspace(start, stop, num) - num points from start to stop (INCLUSIVE)
arr1 = np.linspace(0, 10, 5)
print("linspace(0, 10, 5):")
print(arr1)
print("Spacing:", arr1[1] - arr1[0])

# 11 points from 0 to 1
arr2 = np.linspace(0, 1, 11)
print("\nlinspace(0, 1, 11):")
print(arr2)

# Common use: creating x values for plotting
x = np.linspace(0, 2*np.pi, 100)  # 100 points from 0 to 2π
print("\nlinspace(0, 2π, 100):")
print(f"First 5 values: {x[:5]}")
print(f"Last 5 values: {x[-5:]}")
print(f"Total points: {len(x)}")

# Return the spacing
arr3, step = np.linspace(0, 10, 5, retstep=True)
print(f"\nlinspace(0, 10, 5) with retstep=True:")
print(f"Array: {arr3}")
print(f"Step size: {step}")

linspace(0, 10, 5):
[ 0.   2.5  5.   7.5 10. ]
Spacing: 2.5

linspace(0, 1, 11):
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

linspace(0, 2π, 100):
First 5 values: [0.         0.06346652 0.12693304 0.19039955 0.25386607]
Last 5 values: [6.02931923 6.09278575 6.15625227 6.21971879 6.28318531]
Total points: 100

linspace(0, 10, 5) with retstep=True:
Array: [ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


### Key Differences: arange vs linspace

| Feature | `arange` | `linspace` |
|---------|----------|------------|
| Parameters | start, stop, **step** | start, stop, **num** |
| Includes stop | ❌ No | ✅ Yes |
| You specify | Step size | Number of points |
| Best for | Known step size | Known number of points |

In [22]:
# ===== COMPARISON =====
print("arange(0, 10, 2):")
print(np.arange(0, 10, 2))  # Step=2, stop NOT included

print("\nlinspace(0, 10, 5):")
print(np.linspace(0, 10, 5))  # 5 points, stop IS included

arange(0, 10, 2):
[0 2 4 6 8]

linspace(0, 10, 5):
[ 0.   2.5  5.   7.5 10. ]


## 6. Random Number Generation

NumPy has powerful tools for generating random numbers. We'll focus on two important distributions:

### Random Module Setup

NumPy has a new random API (`np.random.default_rng()`). We'll use both the legacy and new methods:

In [23]:
# Create a random number generator (new API)
rng = np.random.default_rng(seed=42)  # seed for reproducibility

# You can also use the legacy API
np.random.seed(42)  # Set seed for legacy functions

### Uniform Distribution

The **uniform distribution** generates random numbers where all values in a range are equally likely:

In [24]:
# ===== UNIFORM DISTRIBUTION =====

# Generate random floats between 0 and 1
uniform_01 = np.random.random(5)
print("5 random floats [0, 1):")
print(uniform_01)

# Generate random floats in a specific range [low, high)
uniform_range = np.random.uniform(low=10, high=20, size=5)
print("\n5 random floats [10, 20):")
print(uniform_range)

# Generate a 2D array of random values
uniform_2d = np.random.uniform(0, 1, size=(3, 4))
print("\n3x4 array of random floats [0, 1):")
print(uniform_2d)

# Using the new API
rng = np.random.default_rng(seed=42)
uniform_new = rng.uniform(low=0, high=10, size=5)
print("\n5 random floats [0, 10) using new API:")
print(uniform_new)

# Random integers (discrete uniform distribution)
random_ints = np.random.randint(low=1, high=100, size=10)
print("\n10 random integers [1, 100):")
print(random_ints)

5 random floats [0, 1):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

5 random floats [10, 20):
[11.5599452  10.58083612 18.66176146 16.01115012 17.08072578]

3x4 array of random floats [0, 1):
[[0.02058449 0.96990985 0.83244264 0.21233911]
 [0.18182497 0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289 0.13949386]]

5 random floats [0, 10) using new API:
[7.73956049 4.3887844  8.5859792  6.97368029 0.94177348]

10 random integers [1, 100):
[92 60 80 15 62 62 47 62 51 55]


### Gaussian (Normal) Distribution

The **Gaussian** or **normal distribution** is the famous bell curve. It's characterized by:
- **Mean (μ)**: Center of the distribution
- **Standard deviation (σ)**: Spread of the distribution

In [25]:
# ===== GAUSSIAN (NORMAL) DISTRIBUTION =====

# Standard normal distribution (mean=0, std=1)
standard_normal = np.random.randn(5)
print("5 samples from standard normal (μ=0, σ=1):")
print(standard_normal)

# Normal distribution with custom mean and std
# normal(mean, std, size)
custom_normal = np.random.normal(loc=100, scale=15, size=10)
print("\n10 samples from normal (μ=100, σ=15):")
print(custom_normal)
print(f"Mean: {np.mean(custom_normal):.2f}")
print(f"Std: {np.std(custom_normal):.2f}")

# Generate a 2D array
normal_2d = np.random.normal(loc=0, scale=1, size=(3, 4))
print("\n3x4 array from standard normal:")
print(normal_2d)

# Using the new API
rng = np.random.default_rng(seed=42)
normal_new = rng.normal(loc=50, scale=10, size=5)
print("\n5 samples from normal (μ=50, σ=10) using new API:")
print(normal_new)

# Generate a large sample to verify distribution
large_sample = np.random.normal(loc=0, scale=1, size=10000)
print("\n--- Large Sample Statistics (10000 points) ---")
print(f"Mean: {np.mean(large_sample):.4f} (expected: 0)")
print(f"Std: {np.std(large_sample):.4f} (expected: 1)")
print(f"Min: {np.min(large_sample):.4f}")
print(f"Max: {np.max(large_sample):.4f}")

5 samples from standard normal (μ=0, σ=1):
[-0.02445518  0.35555132  0.41701111  0.83246186 -0.29339915]

10 samples from normal (μ=100, σ=15):
[ 99.55242146 101.42688676 109.96981514  97.89672254  99.502099
  88.76385215  88.32426989 114.23264287 123.71275879  94.47743588]
Mean: 101.79
Std: 10.64

3x4 array from standard normal:
[[ 0.37556463 -1.19315823 -0.4090519  -0.44674147]
 [ 1.52424163  0.3229998  -1.39341694 -2.17833425]
 [-1.04389641  0.17269371  0.32419877  0.74585954]]

5 samples from normal (μ=50, σ=10) using new API:
[53.0471708  39.60015894 57.50451196 59.40564716 30.48964811]

--- Large Sample Statistics (10000 points) ---
Mean: 0.0102 (expected: 0)
Std: 1.0082 (expected: 1)
Min: -4.0541
Max: 3.6577


### Other Useful Random Functions

In [26]:
# ===== OTHER RANDOM FUNCTIONS =====

# Random choice from an array
options = np.array(['red', 'green', 'blue', 'yellow'])
choice = np.random.choice(options, size=5)
print("5 random choices:", choice)

# Random choice without replacement
sample = np.random.choice(options, size=3, replace=False)
print("\n3 unique random choices:", sample)

# Shuffle an array in place
arr = np.arange(10)
print("\nOriginal array:", arr)
np.random.shuffle(arr)
print("Shuffled array:", arr)

# Random permutation (returns shuffled copy)
arr = np.arange(10)
shuffled = np.random.permutation(arr)
print("\nOriginal (unchanged):", arr)
print("Permutation:", shuffled)

5 random choices: ['blue' 'red' 'red' 'blue' 'green']

3 unique random choices: ['green' 'blue' 'yellow']

Original array: [0 1 2 3 4 5 6 7 8 9]
Shuffled array: [9 7 4 8 5 0 1 2 3 6]

Original (unchanged): [0 1 2 3 4 5 6 7 8 9]
Permutation: [0 3 8 1 9 2 6 5 7 4]


### Reproducibility with Seeds

Setting a seed makes random number generation reproducible:

In [27]:
# ===== RANDOM SEEDS =====
# Same seed = same random numbers

np.random.seed(42)
print("First run with seed=42:")
print(np.random.random(5))

np.random.seed(42)  # Reset to same seed
print("\nSecond run with seed=42 (same values):")
print(np.random.random(5))

np.random.seed(100)  # Different seed
print("\nThird run with seed=100 (different values):")
print(np.random.random(5))

# New API approach
rng = np.random.default_rng(seed=42)
print("\nUsing new API with seed=42:")
print(rng.random(5))

First run with seed=42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Second run with seed=42 (same values):
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Third run with seed=100 (different values):
[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]

Using new API with seed=42:
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


### 🎯 Practice Exercise: Random Sampling

1. Generate 1000 samples from a uniform distribution between 5 and 15. Calculate the mean and verify it's close to 10.
2. Generate 1000 samples from a Gaussian distribution with mean=50 and std=5. Calculate the mean and std.
3. Create a 5x5 matrix of random integers between 1 and 100.
4. Generate 20 points using linspace from 0 to 10, then add Gaussian noise (mean=0, std=0.5) to each point.
5. Create an array of numbers 1-20, shuffle it, and select the first 5 numbers (simulating random sampling without replacement).

In [73]:
# Your code here:

nums = np.random.uniform(low = 5, high = 15, size= 1000)
print(np.mean(nums), np.std(nums))

nums1 = np.random.normal(loc=50, scale=5, size=1000)
print(np.mean(nums1), np.std(nums1))

np.random.randint(1, 100, size= (5,5))

np.linspace(0,10,20) + np.random.normal(loc= 0, scale= 0.5, size= 20)

mat7 = np.arange(1,20)
np.random.shuffle(mat7)
print(mat7)
mat7[:5]


9.823568603050727 2.8958836167558775
50.060518851606226 5.025635383545262
[ 4 16 10 17  5  9 14  8  7  3 12 15 18 11  1  6 19  2 13]


array([ 4, 16, 10, 17,  5])

## Congratulations! 🎉

You've completed the NumPy basics tutorial! You now understand:

✅ **NumPy Arrays** - Creating, properties, and data types  
✅ **Indexing and Slicing** - 1D, 2D, boolean, and fancy indexing  
✅ **Array Operations** - Element-wise operations, ufuncs, and aggregations  
✅ **Matrix Operations** - Element-wise vs matrix multiplication  
✅ **Creating Sequences** - linspace and arange  
✅ **Random Sampling** - Uniform and Gaussian distributions  

## What's Next?

Now that you know NumPy, you're ready for:
- **Data visualization** with Matplotlib
- **Data analysis** with Pandas
- **Machine Learning** with scikit-learn
- **Deep Learning** with TensorFlow or PyTorch

## Key Takeaways

1. **Use NumPy arrays instead of lists** for numerical data - they're faster!
2. **Remember: `*` is element-wise, `@` is matrix multiplication**
3. **Use linspace when you know how many points you need**
4. **Use arange when you know the step size**
5. **Set random seeds** for reproducible results

Keep practicing and experimenting! 💪